### ISSUE TITLE
API alternative

### ISSUE THREAD

**Issue by patrikniebur** [krasimir/navigo-react#3]
Hi there, 
I've created navigo react version for my side project before I had a chance to see this one. For this I've followed well-known [react-router](https://github.com/ReactTraining/react-router) API so usage looks like this:  
```jsx
<NavigoRouter>
    <NavigoSwitch>
      <NavigoRoute path="/" component={LoginPage} />
      <NavigoRedirect to={'/'} />
    </NavigoSwitch>
</NavigoRouter>
``` 
Components can access router instance via `useRouter` hook, rendered routes have `Match` in their props and similarly to react-router it uses `<Link to="/page">Page</Link>` for navigation.
 
Would you be interested to consider this API? I can publish repo so you can have a look if you're interested

**Comment by krasimir** [comment]
Totally yes. The implementation here is definitely not good. I realized that once I tried using it. I'm preparing another major release that will have more or less the same API as react-router.

**Comment by patrikniebur** [comment]
Great I'll try to get it up this weekend and post the link here

**Comment by patrikniebur** [comment]
Here's the repo https://github.com/patrikniebur/navigo-react I've dropped in components and added `example/basicV3` It only contains what I needed for my use case but I can add remaining functionality from current version. As a next steps I could do:  
1. Add existing tests
2. Make sure tests are passing
3. Compare with existing version and add missing functionality  
4. Update docs
5. Make PR for v3?

Let me know what do you think or if you have upcoming version that I could contribute to.

**Comment by patrikniebur** [comment]
Hi @krasimir just checking if you had some thoughts on it?
Thanks!

**Comment by patrikniebur** [comment]
I'm guessing you have your attention somewhere else now so I'm closing this issue. If you need help with this project in the future let me know :)

**Comment by krasimir** [comment]
Hey @patrikniebur, yes I'm up to other things sorry. I'll get back to this some time later for sure.
